name: CI Pipeline

on:
  pull_request:
    branches:
      - Develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Node.js 버전 명시

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --ci --reporters=jest-junit

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./junit.xml
